version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env

volumes:
  static_value:
  media_value:
  postgres_data:
